name: Build and Deploy to Tomcat

on:
  push:
    branches:
      - main  # or change to your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'  # Change based on your project

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Define versioned WAR name
      run: |
        # Example version: ROOT##${{ github.run_number }}.war
        VERSIONED_NAME="ROOT##${{ github.run_number }}.war"
        cp target/*.war "target/$VERSIONED_NAME"
        echo "VERSIONED_NAME=$VERSIONED_NAME" >> $GITHUB_ENV

    - name: Upload versioned WAR via SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.TOMCAT_HOST }}
        username: ${{ secrets.TOMCAT_USER }}
        password: ${{ secrets.TOMCAT_PASS }}
        port: 22
        source: "target/${{ env.VERSIONED_NAME }}"
        target: "/opt/tomcat/webapps/"

    - name: Restart Tomcat (optional)
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.TOMCAT_HOST }}
        username: ${{ secrets.TOMCAT_USER }}
        password: ${{ secrets.TOMCAT_PASS }}
        port: 22
        script: |
          sudo systemctl restart tomcat
